In [2]:
import numpy as np

In [3]:
my_list  = [1,2,3]

In [ ]:
type(my_list)

In [ ]:
myarray = np.array(my_list)
myarray

In [ ]:
np.arange(0,10,2) # Returns evenly spaced value within a given

In [ ]:
np.zeros(shape=(5,5)) # Returns 5 rows 5 columns

In [ ]:
np.ones((2,4))

In [14]:
np.random.seed(101) # Allows to create the same random no each time
arr = np.random.randint(0,100,10)
arr

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [15]:
arr2 = np.random.randint(0,100,10)
arr2

array([ 4, 63, 40, 60, 92, 64,  5, 12, 93, 40])

In [17]:
arr.max() # Returns max value of an array

95

In [18]:
arr.argmax() #returns index of the max value

0

In [19]:
arr.min() # returns min value of array

9

In [20]:
arr.argmin() # returns max value of array

7

In [22]:
arr.mean() # returns mean of array

60.8

In [27]:
arr.reshape(2,5) # reshaped to 2 rows 5 colums


array([[95, 11, 81, 70, 63],
       [87, 75,  9, 77, 40]])

In [29]:
mat = np.arange(0,100).reshape(10,10)
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [30]:
mat.shape

(10, 10)

In [33]:
row= 4
col =6
mat[row, col]

46

In [42]:
mat[:,:2]

array([[ 0,  1],
       [10, 11],
       [20, 21],
       [30, 31],
       [40, 41],
       [50, 51],
       [60, 61],
       [70, 71],
       [80, 81],
       [90, 91]])

In [43]:
mat[:,:2].reshape(5,4)

array([[ 0,  1, 10, 11],
       [20, 21, 30, 31],
       [40, 41, 50, 51],
       [60, 61, 70, 71],
       [80, 81, 90, 91]])

In [45]:
mat[:3,:3] = 0
mat

array([[ 0,  0,  0,  3,  4,  5,  6,  7,  8,  9],
       [ 0,  0,  0, 13, 14, 15, 16, 17, 18, 19],
       [ 0,  0,  0, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [46]:
mynewmat = mat.copy()

In [48]:
mynewmat[0:6,:] = 99
mynewmat

array([[99, 99, 99, 99, 99, 99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99, 99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99, 99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99, 99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99, 99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99, 99, 99, 99, 99, 99],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])